-- ora数据库表结构
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 第二个数据库表结构
DROP TABLE IF EXISTS products;

CREATE TABLE products (
                          id INT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          price DECIMAL(10, 2) NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 第三个数据库表结构
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
                        id INT AUTO_INCREMENT PRIMARY KEY,
                        user_id INT NOT NULL,
                        product_id INT NOT NULL,
                        quantity INT NOT NULL,
                        order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TEST1表结构
DROP TABLE IF EXISTS TEST1;

CREATE TABLE TEST1 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount1 NUMBER(17,3),
  amount2 NUMBER(17,3),
  amount3 NUMBER(17,3),
  amount4 NUMBER(17,3),
  amount5 NUMBER(17,3),
  amount6 NUMBER(17,3),
  amount7 NUMBER(17,3),
  amount8 NUMBER(17,3),
  amount9 NUMBER(17,3),
  amount10 NUMBER(17,3)
);

-- 公式1测试表 (ora = rlcms_pv1 + rlcms_pv2 + rlcms_pv3)
DROP TABLE IF EXISTS FORMULA1_TRUE;
CREATE TABLE FORMULA1_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA1_FALSE;
CREATE TABLE FORMULA1_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA1_NA;
CREATE TABLE FORMULA1_NA
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式2测试表 (ora = rlcms_base)
DROP TABLE IF EXISTS FORMULA2_TRUE;
CREATE TABLE FORMULA2_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA2_FALSE;
CREATE TABLE FORMULA2_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA2_NA;
CREATE TABLE FORMULA2_NA
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式3测试表 (ora = rlcms_base = bscopy_pv1 = bscopy_pv2 = bscopy_pv3)
DROP TABLE IF EXISTS FORMULA3_TRUE;
CREATE TABLE FORMULA3_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA3_FALSE;
CREATE TABLE FORMULA3_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA3_NA;
CREATE TABLE FORMULA3_NA
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式4测试表 (ora = rlcms_pv1 = rlcms_pv2 = rlcms_pv3)
DROP TABLE IF EXISTS FORMULA4_TRUE;
CREATE TABLE FORMULA4_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA4_FALSE;
CREATE TABLE FORMULA4_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA4_NA;
CREATE TABLE FORMULA4_NA
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式5测试表 (ora = rlcms_base = rlcms_pv1 = rlcms_pv2 = rlcms_pv3)
DROP TABLE IF EXISTS FORMULA5_TRUE;
CREATE TABLE FORMULA5_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA5_FALSE;
CREATE TABLE FORMULA5_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA5_NA;
CREATE TABLE FORMULA5_NA
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式6测试表 (ora = rlcms_pv1)
DROP TABLE IF EXISTS FORMULA6_TRUE;
CREATE TABLE FORMULA6_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA6_FALSE;
CREATE TABLE FORMULA6_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA6_NA;
CREATE TABLE FORMULA6_NA
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
); 