-- rlcms_pv2数据库表结构
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(100) NOT NULL,
  address VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 订阅表结构
DROP TABLE IF EXISTS subscriptions;

CREATE TABLE subscriptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  plan_name VARCHAR(50) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TEST4表结构
DROP TABLE IF EXISTS TEST4;

CREATE TABLE TEST4 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value1 VARCHAR(100),
  value2 DECIMAL(15,2),
  value3 TIMESTAMP,
  value4 BOOLEAN,
  value5 VARCHAR(200),
  value6 INT,
  value7 DECIMAL(10,4),
  value8 VARCHAR(50),
  value9 DATE,
  value10 TEXT
);

-- 公式1测试表
DROP TABLE IF EXISTS FORMULA1_TRUE;
CREATE TABLE FORMULA1_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA1_FALSE;
CREATE TABLE FORMULA1_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式4测试表
DROP TABLE IF EXISTS FORMULA4_TRUE;
CREATE TABLE FORMULA4_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA4_FALSE;
CREATE TABLE FORMULA4_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

-- 公式5测试表
DROP TABLE IF EXISTS FORMULA5_TRUE;
CREATE TABLE FORMULA5_TRUE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
);

DROP TABLE IF EXISTS FORMULA5_FALSE;
CREATE TABLE FORMULA5_FALSE
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    amount DECIMAL(10, 2) NOT NULL
); 