spring:
  application:
    name: db-checker
  # 主数据源配置
  datasource:
    hikari:
      # 连接超时时间（毫秒）
      connection-timeout: 60000
      # 最小空闲连接数
      minimum-idle: 8
      # 最大连接数
      maximum-pool-size: 64
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 连接最大生存时间（毫秒）
      max-lifetime: 1800000
      # 查询超时时间（秒）
      connection-test-query: SELECT 1
      # 自动提交
      auto-commit: true
      # 验证超时时间（秒）
      validation-timeout: 5000
    primary:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./data/primary;AUTO_SERVER=TRUE;
      username: sa
      password: 
    # 第二个数据源配置
    secondary:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./data/secondary;AUTO_SERVER=TRUE;
      username: sa
      password: 
    # 第三个数据源配置
    tertiary:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:./data/tertiary;AUTO_SERVER=TRUE;
      username: sa
      password: 

# 日志配置
logging:
  level:
    io.github.luolong47.dbchecker: INFO
    org.springframework.jdbc.core: DEBUG

# 数据库表排除与包含配置
db:
  export:
    # 导出Excel文件的目录，默认为当前目录
    directory: ./export
  exclude:
    # 要排除的schema列表，默认排除INFORMATION_SCHEMA
    schemas: INFORMATION_SCHEMA
    # 要排除的表名前缀
    table-prefixes: SYS_,sys_
  include:
    # 明确要包含的表，即使它们符合排除条件
    # 格式：表名 或 表名@SCHEMA
    # 注意：要明确包含INFORMATION_SCHEMA中的表，必须使用表名@INFORMATION_SCHEMA格式
    tables: PRODUCTS@PUBLIC,ORDERS@PUBLIC,USERS@PUBLIC
